name: restaurants-api-cd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v4.1.7
     - name: Setup .NET Core SDK
       uses: actions/setup-dotnet@v4.0.1 
       with:
         dotnet-version: 8.0.x
     - name: Restore dependencies
       run: dotnet restore
     - name: Build
       run: dotnet build --configuration Release
     - name: Publish
       run: dotnet publish ./src/Restaurants.API/Restaurants.API.csproj --no-build -o ${{env.DOTNET_ROOT}}/api
     # in case buid and deploy-dev runs on different agents
     - name: Upload a Build Artifact
       uses: actions/upload-artifact@v4.3.1
       with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api
  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Artifact download required to ensure deploy-dev has the artifacts because it might be running on a different agent as build
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.3
        with:
          name: api-artifact
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'fnmsantiago-restaurants-api-dev'
          publish-profile:  ${{ secrets.PUBLISH_PROFILE_DEV }}
  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-dev
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.3
        with:
          name: api-artifact
      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.0
        with:
          app-name: 'fnmsantiago-restaurants-api-prod'
          publish-profile:  ${{ secrets.PUBLISH_PROFILE_PROD }}


  
